version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass hello_redis
    volumes:
      - cache:/data

  api:
    build: .
    depends_on:
      - cache
    ports:
      - '80:80'
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: hello_redis
volumes:
  cache:
    driver: local